# Generated by Django 4.2.16 on 2024-10-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='crosses_antimeridian',
            field=models.BooleanField(default=False, verbose_name='Пересекает антимеридиан'),
        ),
    ]
